### ISSUE TITLE
Problem running a python using your compiled geckodriver

### ISSUE THREAD

**Issue by speusippo** [d0ku/GeckoDriver_ARMv6#1] opened 2017-09-17 08:19 UTC
Hello,
first of all many thanks for your compiled geckodriver for armv6!!! :-)

I tried to download it and use it but when running a python I got this error:

pi@raspberrypi:~ $ python finestre.py
Traceback (most recent call last):
  File "finestre.py", line 4, in <module>
    browser = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

The python source is:

#!/usr/bin/env python3
from selenium import webdriver
browser = webdriver.Firefox()
browser.get('http://seleniumhq.org/')

Do you have any advice to make it work?

**Comment by dezeroku** [comment] 2017-09-17 10:46
Hi, at first you could try to start it using "python3 finestre.py", it should use newest python and it worked for me.  btw the first line of your code (I mean #! stuff) doesn't look too good. run "which python3" in terminal and paste output after the #!, this should work better. If it still doesn't work please write me what firefox version are you using.

UPDATE:
I recommend using 0.18 binary (available in branch in my repo) with raspberry pi zero W, that version works out of the box with firefox 52.3.0, which I think is the newest available in raspbian repo

**Comment by dezeroku** [comment] 2017-09-21 16:47
@speusippo Hi, did you make it work?

**Comment by dezeroku** [comment] 2017-09-27 20:16
Closed as python/selenium problem, not caused by GeckoDriver.

**Closed as completed** 2017-09-27 20:15 UTC
Labels: help wanted
